"""Description of changes

Revision ID: 9119cbe666c8
Revises: f673dd58665c
Create Date: 2023-08-22 21:33:15.087622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9119cbe666c8'
down_revision = 'f673dd58665c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('type', sa.String(), nullable=False))
    with op.batch_alter_table('cars') as batch_op:
        batch_op.alter_column('color', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars') as batch_op:
        batch_op.alter_column('color', existing_type=sa.String(), nullable=True)
    op.drop_column('cars', 'type')
    # ### end Alembic commands ###

